### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/helm-postgresql#2]
Bitnami added LDAP support: https://github.com/helm/charts/tree/master/stable/postgresql#710, https://github.com/bitnami/bitnami-docker-postgresql/issues/154

I porpose to archive this repo. But the sync between ldap and postgresql is for the moment manual with this Helm Chart... 

2 options:

* make a PR into https://github.com/helm/charts/tree/master/stable/postgresql with https://github.com/cetic/pg-ldap-sync-docker

* create a Helm Chart for https://github.com/cetic/pg-ldap-sync-docker

**Comment by kamilgregorczyk** [comment]
Bitnam repo uses their own postgres image and it does not support ARM64

**Comment by bygui86** [comment]
Additionally to that, afaik Bitnami Postgres requires root access and root filesystem writing permissions, or at least the init-container to establish proper folder ownership, which I think is a REALLY BAD IDEA than what's done in this repo (basically doing it in Dockefile during image build).
I really don't like the idea of running a customized Postgres for a use case (Bitnami's) potentially way different than what I need...

**Comment by kamilgregorczyk** [comment]
FYI, you can put custom docker image path to bitnami repo with arm and it will work

**Comment by banzo** [comment]
closing, there is a small text explaining this in the README
